version: "2"

#########################################################
####                   Services                      ####
#########################################################
services:
    ubuntubase:
        build: ./ubuntu-base

    ui:
        build: ./ui
        expose:
            - "8081"
        volumes:
            #- ./logs/:/var/log/nginx/
            - ./ui/html:/var/www/html:ro
        restart: always
        labels:
          container_group: monitoring
        logging:
          driver: syslog
          options:
            syslog-address: udp://${LOGSTASH_ADDR}:5000
            labels: container_group

    api:
        build: ./api
        expose:
            - "3000"
        links:
            - mongodb:db
        volumes:
            #- ./logs/:/var/log/pm2/
            - ./api/app:/var/www/html
        restart: always
        labels:
          container_group: monitoring
        logging:
          driver: syslog
          options:
            syslog-address: udp://${LOGSTASH_ADDR}:5000
            labels: container_group
    mongodb:
        build: ./mongodb
        expose:
          - "3333"
        volumes:
            #- ./logs/:/var/log/mongodb/
            - ./mongodb/db:/data/db
        restart: always
        labels:
          container_group: monitoring
        logging:
          driver: syslog
          options:
            syslog-address: udp://${LOGSTASH_ADDR}:5000
            labels: container_group

    nginxreverseproxy:
        build: ./nginx-reverse-proxy
        expose:
            - "80"
            - "443"
        links:
            - ui
            - api
        ports:
            - "80:80"
        #volumes:
            #- ./logs/:/var/log/nginx/
        restart: always
        labels:
          container_group: monitoring
        logging:
          driver: syslog
          options:
            syslog-address: udp://${LOGSTASH_ADDR}:5000
            labels: container_group

#########################################################
####                   Networking                    ####
#########################################################

# Extra-network is necessary to have a dedicated IP for Logstash to forwards log to.
networks:
  default:
    external:
      name: monitoring_logging